const GET_ALL_UPCOMING_MOVIES = 'GET_ALL_UPCOMING_MOVIES';

const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
const GET_MOVIE_CASTS = 'GET_MOVIE_CASTS';

export {GET_ALL_UPCOMING_MOVIES, GET_MOVIE_DETAILS, GET_MOVIE_CASTS};
